### ISSUE TITLE
Rename s3Policies constructor to S3Policies

### ISSUE THREAD

**Issue by reywood** [davidworkman9/s3Policies#4]
This is simply a recommendation that the constructor function be renamed to have an uppercase S. This is in keeping with generally accepted conventions to distinguish between functions that should be called with and without `new`. See [Javascript: The Good Parts](https://books.google.com/books?id=PXa2bby0oQ0C&pg=PA123&lpg=PA123&dq=javascript+constructor+uppercase&source=bl&ots=HJoms1s_hK&sig=hiiWOcdx3aE4tW-ku_rFy2p-5XM&hl=en&sa=X&ei=8BqTVfLOA8-4oQSToKagDw&ved=0CEYQ6AEwBg#v=onepage&q=javascript%20constructor%20uppercase&f=false), [JSLint](https://jslinterrors.com/a-constructor-name-should-start-with-an-uppercase-letter), [ESLint](http://eslint.org/docs/rules/new-cap.html), [JSCS](http://jscs.info/rule/requireCapitalizedConstructors.html).

The old function name can be kept around for backwards compatibility via something simple like:

```javascript
S3Policies = s3Policies = function (accessKey, secretKey) {
```

**Comment by davidworkman9** [comment]
Agreed. Updated and published to atmosphere.
