### ISSUE TITLE
Regions ?

### ISSUE THREAD

**Issue by jm4r7in** [davidworkman9/s3Policies#5]
What about the Regions (non US) ?

I've got a message "The bucket you are attempting to access must be addressed using the specified endpoint. Please send all future requests to this endpoint." and I think it may be because of the non-US Region. Is it possible to specify it somehow ?

**Comment by davidworkman9** [comment]
[Yes](https://github.com/davidworkman9/s3Policies/blob/master/s3Policy.js#L10)! I'll have to update the README, but here's how you would do that.
```
var url = s3.readPolicy('LOCATION', 'BUCKET', SECONDS_BEFORE_TIMEOUT, 'FORCE_FILENAME', 'REGION');
```

**Comment by jm4r7in** [comment]
Hello David,
Thanks for the answer, but it still doesn't work (for a non US region).
I think the issue is with the line 27 :
`var url = 'https://'+regionDomain+'.amazonaws.com/';`
I think it would work if you'd remove it.

Btw, in the README, you write:
`var url = s3.readPolicy('LOCATION', 'BUCKET', SECONDS_BEFORE_TIMEOUT, 'FORCE_FILENAME', 'REGION');`
'LOCATION' is confusing, and I would suggest to replace it by 'FILE_KEY'.

**Comment by jm4r7in** [comment]
Hello David,

When you write:
`var url = s3.readPolicy('LOCATION', 'BUCKET', SECONDS_BEFORE_TIMEOUT, 'FORCE_FILENAME', 'REGION');`
2 points a bit confusing:
- I would suggest to replace 'LOCATION' by something like 'FILE_KEY'
- I would suggest to replace 'REGION' by something like 'ENDPOINT'
  According to http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_region the region would be (for me) "eu-west-1", but I need to set the var to "s3-eu-west-1".

**Comment by davidworkman9** [comment]
Thanks for the feedback @jm4r7in,

I've renamed LOCATION to KEY.

It appears that all the endpoint names on the link you sent are just the region names with `s3-` prepended to it, so I think I'll just do a test, if REGION was passed in and it doesn't start with `s3-` then tack it on the front.

**Comment by jm4r7in** [comment]
Thanks for the package @davidworkman9 :+1:

**Comment by jm4r7in** [comment]
You can also add `meteor add mrt:s3policies` to the readme, and maybe a link to `https://atmospherejs.com/mrt/s3policies`.
